# Generated by Django 3.1.4 on 2020-12-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=50)),
                ('Desc', models.CharField(max_length=500)),
                ('Loc', models.CharField(max_length=50)),
                ('fromDate', models.DateField()),
                ('fromTime', models.TimeField()),
                ('toDate', models.DateField()),
                ('toTime', models.TimeField()),
                ('regEndDate', models.DateField()),
                ('regEndTime', models.TimeField()),
                ('regEmail', models.EmailField(max_length=254)),
                ('regPswd', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
    ]
