# Generated by Django 3.1.4 on 2020-12-27 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_event_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='poster',
        ),
    ]
