# Generated by Django 3.1.4 on 2020-12-28 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201227_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='proofLink',
        ),
    ]
